services:
  - type: web
    name: eqtl-gd-smartcheck
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: EMBEDDING_DIMENSIONS
        value: "1536"
    autoDeploy: true